### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mrturcot** [scrawl/osg#20]
hey I'm getting this error building on linux

`make: *** [Makefile:136: all] Error 2`

136   │     $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all

[osg_cmake_config.txt](https://github.com/OpenMW/osg/files/9760231/osg_cmake_config.txt)
[osg_build_log.txt](https://github.com/OpenMW/osg/files/9760248/osg_build_log.txt)

**Comment by mrturcot** [comment]
no movement closing

**Comment by AnyOldName3** [comment]
Just seen this. The errors are due to you using an incompatible FFMPEG version.

**Comment by mrturcot** [comment]
> Just seen this. The errors are due to you using an incompatible FFMPEG version.

Ohhh thank you, makes sense for me now :) cheers

**Comment by Maxsuragi** [comment]
> Just seen this. The errors are due to you using an incompatible FFMPEG version.

With no indication of which ffmpeg versions ARE compatible to my knowledge, how am I to resolve this neatly? I'm currently using the latest version of 7.0.1. Forgive me if it's a silly question but I'm really quite lost on this issue.

**EDIT**
fixed now, i used jiapei100's osgPlugins 7.0.1 ffmpeg compatible commit found here: https://github.com/openscenegraph/OpenSceneGraph/pull/1281/commits/26f6c9b5a63715dde3c9f85c8faf035d3ec0f657
